### PR TITLE
Fix cpu format

### PR DESCRIPTION
**Pull request by alexeykazakov**

### CODE REVIEW

**Review by dipak-pawar — APPROVED** [review]

**Comment by alexeykazakov** [comment]
[test]

**Comment by alexeykazakov** [comment]
@nurali-techie can you please take a look at the build failure?

**Comment by nurali-techie** [comment]
@alexeykazakov build https://ci.centos.org/job/devtools-fabric8-oso-proxy/163/console was failing with error `flag provided but not defined: -test.v`

**Pull request merged**
